plugins:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
      tests_patterns:
        - src/test/java/**

exclude_patterns:
- "src/test/java"
- "src/test/resources"